### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [jeromescuggs/jerome-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by jeromescuggs** [comment]
done, and done! the awesome lists have been a huge resource and help for me as i stumble around in my pursuit of my various hobbies, and i know it's not too much in the grand scheme of things, but i am excited that my humble change to a line of code is even worth consideration for inclusion on one such list. 

i suppose i should close this, but i am just way too southern to shut the door in someone's face like that :P i wound up going with an MIT license, only because i am unsure if the 'WTF' license is actually a real thing.

**Comment by unixorn** [comment]
Thanks, added.
